#include "connection_processor_configuration.h"

using namespace affix_services;

connection_processor_configuration::connection_processor_configuration(

)
{

}

connection_processor_configuration::connection_processor_configuration(
	const bool& a_pending_authentication_enable_timeout,
	const uint64_t& a_pending_authentication_maximum_idle_time_in_seconds,
	const bool& a_authenticated_connection_enable_disconnect_after_maximum_idle_time,
	const uint64_t& a_authenticated_connection_maximum_idle_time_in_seconds
) :
	m_pending_authentication_enable_timeout(a_pending_authentication_enable_timeout),
	m_pending_authentication_maximum_idle_time_in_seconds(a_pending_authentication_maximum_idle_time_in_seconds),
	m_authenticated_connection_enable_disconnect_after_maximum_idle_time(a_authenticated_connection_enable_disconnect_after_maximum_idle_time),
	m_authenticated_connection_maximum_idle_time_in_seconds(a_authenticated_connection_maximum_idle_time_in_seconds)
{

}

connection_processor_configuration connection_processor_configuration::import_from_file(
	const std::string& a_file_path
)
{
	return connection_processor_configuration{};
}
